# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Poole
tagline:          The Jekyll Butler
url:              http://jeffo27.github.io
paginate:         1
baseurl:          http://jeffo27.github.io/poole
author:
  name:           jeffo27
  url:        
  email:        

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
